spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:prography
    username: sa
    password:
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform

